---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.0.21/24
      routes:
        - to: default
          via: 192.168.0.1
      nameservers:
          addresses: [192.168.0.1, 8.8.8.8]